name: Get Commit ID
on:
    push:
        branches: feature/GetCommitID
    workflow_dispatch:
jobs:
    Install_Packages:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                fetch-depth: '0'
            - name: Fetch latest SHA
              run: echo $(git rev-parse main) >> ${{secrets.COMMIT_ID}}
