name: Salesforce CI/CD Workflow

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  SF-Package-Prepartaion:
    runs-on: ubuntu-latest
    steps:        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Salesforce CLI
        run: |
          npm install @salesforce/cli --global
    
      - name: Checkout GitHub
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
            ref: "${{ github.head_ref }}"
            token: "${{ secrets.GH_PAT }}"

      - name: Get Source and Target Branch names
        run: |
          echo TARGET_BRANCH=${{ github.base_ref }} >> $GITHUB_ENV
          echo SOURCE_BRANCH=${{ github.head_ref }} >> $GITHUB_ENV
      
      - name: Checkout TARGET BRANCH
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
            ref: "${{ github.base_ref }}"
            path: TargetBranchPath
            token: "${{ secrets.GH_PAT }}"

      - name: Get Delta Files for PR
        if: github.event_name == 'pull_request'
        run: |
            echo $(git diff --name-only --diff-filter=d origin/main HEAD | grep 'force-app' > delta-salesforce.txt)
            echo $(git diff --name-only --diff-filter=D origin/main HEAD | grep 'force-app' > delta-destructive-sf.txt)

      - name: Get Delta Files for Merge
        if: github.event_name != 'pull_request'
        run: |
            last-successful-commit=$(gh run list --status "Success" -e "pull_request" --json headSha,conclusion | jq -r '.[] | select(.conclusion == "success") | .headsha' | head -1)
            echo $last-successful-commit
            echo " "
            echo $(git diff --name-only --diff-filter=d HEAD last-successful-commit | grep 'force-app' > delta-salesforce.txt)
            echo $(git diff --name-only --diff-filter=D HEAD last-successful-commit | grep 'force-app' > delta-destructive-sf.txt)

      - name: Generate Delta Package
        run: |
            if [ -s "delta-salesforce.txt" ];
            then
              sh scripts/Shell/deltaPackage.sh
              cat package/package.xml
            else
              mkdir package
              echo "<?xml version="1.0" encoding="UTF-8"?>
              <Package xmlns="http://soap.sforce.com/2006/04/metadata">
                  <version>59.0</version>
              </Package>" > package/package.xml
            fi
      - name: Destructive for PR
        env:
          GH_TOKEN: "${{ secrets.GH_PAT }}"
        if: github.event_name == 'pull_request'
        run: |
            if [ -s "delta-destructive-sf.txt" ];
            then
              sh scripts/Shell/destructiveChanges.sh "TargetBranchPath"
            else
              echo "<?xml version="1.0" encoding="UTF-8"?>
              <Package xmlns="http://soap.sforce.com/2006/04/metadata">
                  <version>59.0</version>
              </Package>" > package/destructiveChanges.xml
            fi
      - name: Generate Destructive Delta for Merge PR
        env:
          GH_TOKEN: "${{ secrets.GH_PAT }}"
        if: github.event_name != 'pull_request'
        run: |
            if [ -s "delta-destructive-sf.txt" ];
            then
              sh scripts/Shell/destructiveMerge.sh
            else
              echo "<?xml version="1.0" encoding="UTF-8"?>
              <Package xmlns="http://soap.sforce.com/2006/04/metadata">
                  <version>59.0</version>
              </Package>" > package/destructiveChanges.xml
            fi
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
            name: sf-package
            path: package/*
      - name: Display Delta Package
        run: |
            if [ -s "package/package.xml" ];
            then
              echo "--------------Package XML------------------"
              cat package/package.xml
            fi
            if [ -s "package/destructiveChanges.xml" ];
            then
              echo "--------------Destructive Changes XML------------------"
              cat package/destructiveChanges.xml
            fi

  SF-VALIDATION-DEPLOYMENT:
    name: Validation/Deployment
    needs: SF-Package-Prepartaion
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.GH_PAT }}"
      - name: Install Salesforce CLI
        run: |
            npm install @salesforce/cli --global

      - name: Authenticate with DevHub (CI org)
        run: |
          SFDX_AUTH_URL="force://PlatformCLI::5Aep861sDdjizbO.v6wWFLlMMdrS7H5xSuq2_Zr1WIl43Eqn75jBd0u8AhM2HjFXu08OphqB5YYim2bSHhaoKXV@deloittecom78-dev-ed.develop.my.salesforce.com"
          echo $SFDX_AUTH_URL > auth-url.txt
          sf org login sfdx-url --sfdx-url-file auth-url.txt

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: sf-package
          path: package/

      - name: Validate for Pull Request
        if: github.event_name == 'pull_request'
        run: |
          count=$(cat package/package.xml | grep -c "<types>") || true
          echo $count
          if [ $count -ne 0 ];
          then
            countd=$(cat package/destructiveChanges.xml | grep -c "<types>") || true
            echo $countd
            if [ $countd -ne 0 ];
            then
              sf project deploy start -x package/package.xml -l NoTestRun --dry-run --target-org "lsomanath12@deloitte.com" --post-destructive-changes package/destructiveChanges.xml --ignore-warnings
            else
              sf project deploy start -x package/package.xml -l NoTestRun --dry-run --target-org "lsomanath12@deloitte.com"
            fi
          else
            echo "No Source Backed Components Found"
          fi

      - name:  Deploy-on-merge
        if: github.event_name == 'push'
        run: |
          count=$(cat package/package.xml | grep -c "<types>") || true
          if [ ! $count ];
          then
            countd=$(cat package/destructiveChanges.xml | grep -c "<types>") || true
            if [ ! $countd ];
            then
              sf project deploy start -x package/package.xml -l NoTestRun --target-org "lsomanath12@deloitte.com" --post-destructive-changes package/destructiveChanges.xml --ignore-warnings
            else
              sf project deploy start -x package/package.xml -l NoTestRun --target-org "lsomanath12@deloitte.com"
            fi
          else
            echo "No Source Backed Components Found"
          fi

