name: Validation of Deployment
on: 
    pull_request:
        branches: main
    workflow_dispatch:
jobs:
    Install_Packages:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install Dependencies
              run: npm install --global oclif
            - name: Install Salesforce CLI
              run: npm install --global sfdx-cli@latest
            - name: Install SFDX Delta
              run: echo y | sfdx plugins:install sfdx-git-delta
            - name: Authorise Salesforce Org
              run: sfdx auth:sfdxurl:store -f authorise -s -a ManideepOrg
            - name: Display Commit ID
              run: echo ${{github.COMMIT_ID}}
            - name: Get Delta
              run: sfdx sgd:source:delta --to HEAD --from ${{github.COMMIT_ID}} --output .
            - name: Display Package.xml
              run: cat package/package.xml
            - name: Validate Source Code
              run: sfdx force:source:deploy -x package/package.xml -u kmanideep@deloitte.com -l ${{secrets.SF_TESTLEVEL}} -c -w 60 --verbose
